export const CREATE_BOOK = 'CREATE_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const TOGGLE_HIDDEN = 'TOGGLE_HIDDEN';